# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d74b3aae0ddcaed29c79fdbe4fb3e18f9c4fc7e140af0213dd1288d474093d42138423d868b1fb1a65cb11c42975b99f393ebf6b18b2db0b92babe92d348ce0c

test:
  secret_key_base: 0c733f61580d582bdb9e7d6de0eebef73749af5808c9da2df033c187bbb63a4dd0cacfdeb95d3580ecb42f7a1eb3167b2d111e0bf6304f10c6400b994573ae12

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
